extends Node
# This singleton will most likely be gutted at some point in favor of having its functionality spread out so
# it isn't handling everything related to potion making

# TODO: Have an external script that will convert all ID tags from the spread sheet into consts

enum AttributeID {
	ATTR_HEALING,
	ATTR_MANA,
	ATTR_PARALYSIS,
	ATTR_FOCUS,
	ATTR_STRENGTH,
	ATTR_PERCEPTION,
	ATTR_ENDURANCE,
	ATTR_CHARISMA,
	ATTR_INTELLIGENCE,
	ATTR_AGILITY,
	ATTR_LUCK,
	ATTR_FLAME,
	ATTR_FROST,
	ATTR_SHOCK,
	ATTR_WIND,
	ATTR_EARTH,
	ATTR_WATER,
	ATTR_PURIFICATION,
	ATTR_ANTIDOTE,
	ATTR_SLEEP,
	ATTR_CALMING,
	ATTR_LIGHT,
	ATTR_DARK,
	ATTR_PAIN_RELIEF,
}

enum IngredientID{
	INGR_APPLE,
	INGR_GINGER,
	INGR_LEMON,
	INGR_CHAMOMILE,
	INGR_PEPPERMINT,
	INGR_GARLIC,
	INGR_HONEY,
	INGR_COFFEE_BEAN,
	INGR_GINSENG,
	INGR_LAVENDER,
	INGR_SAGE,
	INGR_ROSEMARY,
	INGR_CINNAMON,
	INGR_CHILI,
	INGR_SEA_SALT,
	INGR_CLOVER,
	INGR_WILLOW_BARK,
	INGR_POPPY_RESIN,
	INGR_MOONCAP,
	INGR_EMBERROOT,
	INGR_FROSTMINT,
	INGR_SPARK_THISTLE,
	INGR_WHISPER_REED,
	INGR_IRONMOSS,
	INGR_DEEPWATER_KELP,
	INGR_SILVERLEAF,
	INGR_SHADEBERRY,
	INGR_SCHOLARS_MOREL,
	INGR_NIMBLEFERN,
	INGR_VELVET_ROSE,
	INGR_STONECAP,
	INGR_BASILISK_SCALE,
	INGR_SPIDER_LILY,
	INGR_SIREN_PEARL,
	INGR_PHOENIX_ASH,
	INGR_ICE_WYRM_SCALE,
	INGR_STORMGLASS_DUST,
	INGR_SAINTS_BALM,
	INGR_DREAM_ORCHID,
	INGR_VOID_TRUFFLE,
}

enum PotionID {
	POT_HEALING,
	POT_MANA,
	POT_PARALYSIS,
	POT_FOCUS,
	POT_STRENGTH,
	POT_PERCEPTION,
	POT_ENDURANCE,
	POT_CHARISMA,
	POT_INTELLIGENCE,
	POT_AGILITY,
	POT_LUCK,
	POT_FLAME,
	POT_FROST,
	POT_SHOCK,
	POT_WIND,
	POT_EARTH,
	POT_WATER,
	POT_PURIFICATION,
	POT_ANTIDOTE,
	POT_SLEEP,
	POT_CALMING,
	POT_LIGHT,
	POT_DARK,
	POT_PAIN_RELIEF,
}

enum ProcessID {
	PROC_CHOP,
	PROC_GRIND,
	PROC_PRESS,
	PROC_BOIL,
	PROC_DRY,
	PROC_FREEZE,
	PROC_FRY,
	PROC_DISTILL,
} 

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.


func read_ingredient_data() -> void:
	pass
